name: "GraphQl"

on:
  workflow_dispatch:
    inputs:
      request:
        description: 'GraphQl request query'     
        required: true
        default: "{ \\\"query\\\": \\\"query { viewer { login } }\\\" }"

jobs:
  graphQl:
    name: "GraphQl"
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Setup Kotlin
        uses: fwilhe2/setup-kotlin@main
        with:
          version: '1.4.30'
          install-native: false

      - name: Run GraphQl Script
        run: kotlin graphql.main.kts "${{ github.token }}" "${{ github.event.inputs.request }}" 