name: "QrCodeGen"

on:
  workflow_dispatch:
    inputs:
      text:
        description: "Text to be encode"
        required: true
        default: "Hello World!"
      type:
        description: "Output type: SVG | PNG"
        required: false
        default: "SVG"
      output:
        description: "Output file name without extension"
        required: false
        default: "output"

jobs:
  qrCodeGen:
    name: "QrCodeGen"
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Setup Kotlin
        uses: fwilhe2/setup-kotlin@main
        with:
          version: '1.4.30'
          install-native: false

      - name: Run QrCode Script
        run: kotlin qrcode.main.kts "${{ github.event.inputs.text }}" "--output=${{ github.event.inputs.output }}" "--type=${{ github.event.inputs.type }}"
 
      - name: Upload pixeldrain
        if: ${{ github.event.inputs.type == 'PNG' }}
        run: |
          wget https://raw.githubusercontent.com/Fornax96/pdup/master/pdup -O pdup
          chmod +x ./pdup
          ./pdup ${{ env.qrOutput }}

      - name: Upload output
        uses: actions/upload-artifact@v1
        with:
          name: qrcode_output
          path: ${{ env.qrOutput }}
