name: "Sample"

on:
  workflow_dispatch:
    inputs:
      hello:
        description: 'Your name please?'     
        required: true
        default: 'ratabb'
  
jobs:
  sample:
    name: "Sample"
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Setup Kotlin
        uses: fwilhe2/setup-kotlin@main
        with:
          version: '1.4.30'
          install-native: false

      - name: Run Sample Script
        run: kotlin sample.main.kts "${{ github.event.inputs.hello }}"

