name: "Sample"

on:
  workflow_dispatch:
    inputs:
      hello:
        description: 'Your name please?'     
        required: true
        default: 'ratabb'

env:
  GITHUB_TOKEN: ${{ github.token }}
  
jobs:
  sample:
    name: "Sample"
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        
      - name: Install JDK
        uses: actions/setup-java@v1
        with:
          java-version: '14'

      - name: Fetch SDKMan
        run: curl -s https://get.sdkman.io -o install-sdkman

      - name: Install SDKMan
        run: |
          chmod u+x install-sdkman
          ./install-sdkman          
          echo "SDKMAN_DIR=$HOME/.sdkman" >> $GITHUB_ENV

      - name: Install Kotlin Scripting
        run: |
          . $SDKMAN_DIR/bin/sdkman-init.sh
          sdk install kotlin          
          echo "$SDKMAN_DIR/candidates/kotlin/current/bin" >> $GITHUB_PATH

      - name: Make executable and run Script
        run: |
          chmod +x ./sample.main.kts
          ./sample.main.kts "${{ github.event.inputs.hello }}"

